AGGREGATE_PROVIDER_ID = "KGK"
AGGREGATE_PROVIDER_ORGANIZATION = {
    "name_de": "Konferenz der kantonalen Geoinformations- und Katasterstellen",
    "name_fr": "Conférence des services cantonaux de la Géoinformation et du Cadastre",
    "name_en": "Konferenz der kantonalen Geoinformations- und Katasterstellen",
    "name_it": "Conferenza dei servizi cantonali per la Geoinformazione e del Catasto",
    "name_rm": "Conferenza dals posts chantunals da Geoinfurmaziun e Cataster",
    "acronym_de": "KGK",
    "acronym_fr": "CGC",
    "acronym_en": "KGK",
    "acronym_it": "CGC",
    "acronym_rm": "CGC",
}
AGGREGATE_PROVIDER_CONTACT = {
    "name_de": "Geschäftsstelle KGK-CGC",
    "name_fr": "Centre opérationnel KGK-CGC",
    "name_en": "",
    "name_it": "Direzione operativa KGK-CGC",
    "name_rm": "",
    "email": "geodienste@kgk-cgc.ch",
    "phone": "+41 31 300 09 20",
    "address_delivery_point": "Haus der Kantone, Speichergasse 6, Postfach",
    "address_postal_code": "3001",
    "address_city": "Bern",
    "address_country": "CH",
    "url_de": "https://kgk-cgc.ch/",
    "url_fr": "https://kgk-cgc.ch/fr",
    "url_en": "",
    "url_it": "https://kgk-cgc.ch/it",
    "url_rm": "",
    "legacy_contact": (
        "Geschäftsstelle KGK-CGC\n"
        "Haus der Kantone\n"
        "Speichergasse 6\n"
        "Postfach\n"
        "CH-3001 Bern\n"
        "Tel. +41 31 300 09 20\n"
        "geodienste@kgk-cgc.ch\n"
    ),
}

CANTONAL_PROVIDER_ORGANIZATIONS = {
    "AG": {
        "name_de": "geodienste Aargau",
        "name_fr": "geodienste Argovie",
        "name_it": "geodienste Argovia",
        "name_rm": "geodienste Argovia",
        "name_en": "geodienste Aargau",
        "acronym_de": "AG",
        "acronym_fr": "AG",
        "acronym_en": "AG",
        "acronym_it": "AG",
        "acronym_rm": "AG",
    },
    "AI": {
        "name_de": "geodienste Appenzell Innerrhoden",
        "name_fr": "geodienste Appenzell Rhodes-Intérieures",
        "name_it": "geodienste Appenzello Interno",
        "name_rm": "geodienste Appenzell Dadens",
        "name_en": "geodienste Appenzell Innerrhoden",
        "acronym_de": "AI",
        "acronym_fr": "AI",
        "acronym_en": "AI",
        "acronym_it": "AI",
        "acronym_rm": "AI",
    },
    "AR": {
        "name_de": "geodienste Appenzell Ausserrhoden",
        "name_fr": "geodienste Appenzell Rhodes-Extérieures",
        "name_it": "geodienste Appenzello Esterno",
        "name_rm": "geodienste Appenzell Dadora",
        "name_en": "geodienste Appenzell Ausserrhoden",
        "acronym_de": "AR",
        "acronym_fr": "AR",
        "acronym_en": "AR",
        "acronym_it": "AR",
        "acronym_rm": "AR",
    },
    "BE": {
        "name_de": "geodienste Bern",
        "name_fr": "geodienste Berne",
        "name_it": "geodienste Berna",
        "name_rm": "geodienste Berna",
        "name_en": "geodienste Bern",
        "acronym_de": "BE",
        "acronym_fr": "BE",
        "acronym_en": "BE",
        "acronym_it": "BE",
        "acronym_rm": "BE",
    },
    "BL": {
        "name_de": "geodienste Basel-Landschaft",
        "name_fr": "geodienste Bâle-Campagne",
        "name_it": "geodienste Basilea Campagna",
        "name_rm": "geodienste Basilea-Champagna",
        "name_en": "geodienste Basel-Landschaft",
        "acronym_de": "BL",
        "acronym_fr": "BL",
        "acronym_en": "BL",
        "acronym_it": "BL",
        "acronym_rm": "BL",
    },
    "BS": {
        "name_de": "geodienste Basel-Stadt",
        "name_fr": "geodienste Bâle-Ville",
        "name_it": "geodienste Basilea Città",
        "name_rm": "geodienste Basilea-Citad",
        "name_en": "geodienste Basel-Stadt",
        "acronym_de": "BS",
        "acronym_fr": "BS",
        "acronym_en": "BS",
        "acronym_it": "BS",
        "acronym_rm": "BS",
    },
    "FR": {
        "name_de": "geodienste Freiburg",
        "name_fr": "geodienste Fribourg",
        "name_it": "geodienste Friburgo",
        "name_rm": "geodienste Friburg",
        "name_en": "geodienste Fribourg",
        "acronym_de": "FR",
        "acronym_fr": "FR",
        "acronym_en": "FR",
        "acronym_it": "FR",
        "acronym_rm": "FR",
    },
    "GE": {
        "name_de": "geodienste Genf",
        "name_fr": "geodienste Genève",
        "name_it": "geodienste Ginevra",
        "name_rm": "geodienste Genevra",
        "name_en": "geodienste Geneva",
        "acronym_de": "GE",
        "acronym_fr": "GE",
        "acronym_en": "GE",
        "acronym_it": "GE",
        "acronym_rm": "GE",
    },
    "GL": {
        "name_de": "geodienste Glarus",
        "name_fr": "geodienste Glaris",
        "name_it": "geodienste Glarona",
        "name_rm": "geodienste Glaruna",
        "name_en": "geodienste Glarus",
        "acronym_de": "GL",
        "acronym_fr": "GL",
        "acronym_en": "GL",
        "acronym_it": "GL",
        "acronym_rm": "GL",
    },
    "GR": {
        "name_de": "geodienste Graubünden",
        "name_fr": "geodienste Grisons",
        "name_it": "geodienste Grigioni",
        "name_rm": "geodienste Grischun",
        "name_en": "geodienste Graubünden",
        "acronym_de": "GR",
        "acronym_fr": "GR",
        "acronym_en": "GR",
        "acronym_it": "GR",
        "acronym_rm": "GR",
    },
    "JU": {
        "name_de": "geodienste Jura",
        "name_fr": "geodienste Jura",
        "name_it": "geodienste Giura",
        "name_rm": "geodienste Giura",
        "name_en": "geodienste Jura",
        "acronym_de": "JU",
        "acronym_fr": "JU",
        "acronym_en": "JU",
        "acronym_it": "JU",
        "acronym_rm": "JU",
    },
    "LU": {
        "name_de": "geodienste Luzern",
        "name_fr": "geodienste Lucerne",
        "name_it": "geodienste Lucerna",
        "name_rm": "geodienste Lucerna",
        "name_en": "geodienste Lucerne",
        "acronym_de": "LU",
        "acronym_fr": "LU",
        "acronym_en": "LU",
        "acronym_it": "LU",
        "acronym_rm": "LU",
    },
    "NE": {
        "name_de": "geodienste Neuenburg",
        "name_fr": "geodienste Neuchâtel",
        "name_it": "geodienste Neuchâtel",
        "name_rm": "geodienste Neuchâtel",
        "name_en": "geodienste Neuchâtel",
        "acronym_de": "NE",
        "acronym_fr": "NE",
        "acronym_en": "NE",
        "acronym_it": "NE",
        "acronym_rm": "NE",
    },
    "NW": {
        "name_de": "geodienste Nidwalden",
        "name_fr": "geodienste Nidwald",
        "name_it": "geodienste Nidvaldo",
        "name_rm": "geodienste Nidvalden",
        "name_en": "geodienste Nidwalden",
        "acronym_de": "NW",
        "acronym_fr": "NW",
        "acronym_en": "NW",
        "acronym_it": "NW",
        "acronym_rm": "NW",
    },
    "OW": {
        "name_de": "geodienste Obwalden",
        "name_fr": "geodienste Obwald",
        "name_it": "geodienste Obvaldo",
        "name_rm": "geodienste Obwalda",
        "name_en": "geodienste Obwalden",
        "acronym_de": "OW",
        "acronym_fr": "OW",
        "acronym_en": "OW",
        "acronym_it": "OW",
        "acronym_rm": "OW",
    },
    "SG": {
        "name_de": "geodienste St. Gallen",
        "name_fr": "geodienste Saint-Gall",
        "name_it": "geodienste San Gallo",
        "name_rm": "geodienste Son Gagl",
        "name_en": "geodienste St. Gallen",
        "acronym_de": "SG",
        "acronym_fr": "SG",
        "acronym_en": "SG",
        "acronym_it": "SG",
        "acronym_rm": "SG",
    },
    "SH": {
        "name_de": "geodienste Schaffhausen",
        "name_fr": "geodienste Schaffhouse",
        "name_it": "geodienste Sciaffusa",
        "name_rm": "geodienste Schaffusa",
        "name_en": "geodienste Schaffhausen",
        "acronym_de": "SH",
        "acronym_fr": "SH",
        "acronym_en": "SH",
        "acronym_it": "SH",
        "acronym_rm": "SH",
    },
    "SO": {
        "name_de": "geodienste Solothurn",
        "name_fr": "geodienste Soleure",
        "name_it": "geodienste Soletta",
        "name_rm": "geodienste Soloturn",
        "name_en": "geodienste Solothurn",
        "acronym_de": "SO",
        "acronym_fr": "SO",
        "acronym_en": "SO",
        "acronym_it": "SO",
        "acronym_rm": "SO",
    },
    "SZ": {
        "name_de": "geodienste Schwyz",
        "name_fr": "geodienste Schwytz",
        "name_it": "geodienste Svitto",
        "name_rm": "geodienste Sviz",
        "name_en": "geodienste Schwyz",
        "acronym_de": "SZ",
        "acronym_fr": "SZ",
        "acronym_en": "SZ",
        "acronym_it": "SZ",
        "acronym_rm": "SZ",
    },
    "TG": {
        "name_de": "geodienste Thurgau",
        "name_fr": "geodienste Thurgovie",
        "name_it": "geodienste Turgovia",
        "name_rm": "geodienste Turgovia",
        "name_en": "geodienste Thurgau",
        "acronym_de": "TG",
        "acronym_fr": "TG",
        "acronym_en": "TG",
        "acronym_it": "TG",
        "acronym_rm": "TG",
    },
    "TI": {
        "name_de": "geodienste Tessin",
        "name_fr": "geodienste Tessin",
        "name_it": "geodienste Ticino",
        "name_rm": "geodienste Tessin",
        "name_en": "geodienste Ticino",
        "acronym_de": "TI",
        "acronym_fr": "TI",
        "acronym_en": "TI",
        "acronym_it": "TI",
        "acronym_rm": "TI",
    },
    "UR": {
        "name_de": "geodienste Uri",
        "name_fr": "geodienste Uri",
        "name_it": "geodienste Uri",
        "name_rm": "geodienste Uri",
        "name_en": "geodienste Uri",
        "acronym_de": "UR",
        "acronym_fr": "UR",
        "acronym_en": "UR",
        "acronym_it": "UR",
        "acronym_rm": "UR",
    },
    "VD": {
        "name_de": "geodienste Waadt",
        "name_fr": "geodienste Vaud",
        "name_it": "geodienste Vaud",
        "name_rm": "geodienste Vad",
        "name_en": "geodienste Vaud",
        "acronym_de": "VD",
        "acronym_fr": "VD",
        "acronym_en": "VD",
        "acronym_it": "VD",
        "acronym_rm": "VD",
    },
    "VS": {
        "name_de": "geodienste Wallis",
        "name_fr": "geodienste Valais",
        "name_it": "geodienste Vallese",
        "name_rm": "geodienste Valais",
        "name_en": "geodienste Valais",
        "acronym_de": "VS",
        "acronym_fr": "VS",
        "acronym_en": "VS",
        "acronym_it": "VS",
        "acronym_rm": "VS",
    },
    "ZG": {
        "name_de": "geodienste Zug",
        "name_fr": "geodienste Zoug",
        "name_it": "geodienste Zugo",
        "name_rm": "geodienste Zug",
        "name_en": "geodienste Zug",
        "acronym_de": "ZG",
        "acronym_fr": "ZG",
        "acronym_en": "ZG",
        "acronym_it": "ZG",
        "acronym_rm": "ZG",
    },
    "ZH": {
        "name_de": "geodienste Zürich",
        "name_fr": "geodienste Zurich",
        "name_it": "geodienste Zurigo",
        "name_rm": "geodienste Turitg",
        "name_en": "geodienste Zurich",
        "acronym_de": "ZH",
        "acronym_fr": "ZH",
        "acronym_en": "ZH",
        "acronym_it": "ZH",
        "acronym_rm": "ZH",
    },
    "FL": {
        "name_de": "geodienste Liechtenstein",
        "name_fr": "geodienste Liechtenstein",
        "name_it": "geodienste Liechtenstein",
        "name_rm": "geodienste Liechtenstein",
        "name_en": "geodienste Liechtenstein",
        "acronym_de": "FL",
        "acronym_fr": "FL",
        "acronym_en": "FL",
        "acronym_it": "FL",
        "acronym_rm": "FL",
    },
}
