CANTONS = {
    "AG": {
        "de": "Kanton Aargau",
        "fr": "Canton d'Argovie",
        "it": "Cantone di Argovia",
        "rm": "Chantun Argovia",
        "en": "Canton of Aargau",
    },
    "AI": {
        "de": "Kanton Appenzell Innerrhoden",
        "fr": "Canton d'Appenzell Rhodes-Intérieures",
        "it": "Cantone di Appenzello Interno",
        "rm": "Chantun Appenzell Dadens",
        "en": "Canton of Appenzell Innerrhoden",
    },
    "AR": {
        "de": "Kanton Appenzell Ausserrhoden",
        "fr": "Canton d'Appenzell Rhodes-Extérieures",
        "it": "Cantone di Appenzello Esterno",
        "rm": "Chantun Appenzell Dadora",
        "en": "Canton of Appenzell Ausserrhoden",
    },
    "BE": {
        "de": "Kanton Bern",
        "fr": "Canton de Berne",
        "it": "Cantone di Berna",
        "rm": "Chantun Berna",
        "en": "Canton of Bern",
    },
    "BL": {
        "de": "Kanton Basel-Landschaft",
        "fr": "Canton de Bâle-Campagne",
        "it": "Cantone di Basilea Campagna",
        "rm": "Chantun Basilea-Champagna",
        "en": "Canton of Basel-Landschaft",
    },
    "BS": {
        "de": "Kanton Basel-Stadt",
        "fr": "Canton de Bâle-Ville",
        "it": "Cantone di Basilea Città",
        "rm": "Chantun Basilea-Citad",
        "en": "Canton of Basel-Stadt",
    },
    "FR": {
        "de": "Kanton Freiburg",
        "fr": "Canton de Fribourg",
        "it": "Cantone di Friburgo",
        "rm": "Chantun Friburg",
        "en": "Canton of Fribourg",
    },
    "GE": {
        "de": "Kanton Genf",
        "fr": "Canton de Genève",
        "it": "Cantone di Ginevra",
        "rm": "Chantun Genevra",
        "en": "Canton of Geneva",
    },
    "GL": {
        "de": "Kanton Glarus",
        "fr": "Canton de Glaris",
        "it": "Cantone di Glarona",
        "rm": "Chantun Glaruna",
        "en": "Canton of Glarus",
    },
    "GR": {
        "de": "Kanton Graubünden",
        "fr": "Canton des Grisons",
        "it": "Cantone dei Grigioni",
        "rm": "Chantun Grischun",
        "en": "Canton of Graubünden",
    },
    "JU": {
        "de": "Kanton Jura",
        "fr": "Canton du Jura",
        "it": "Cantone del Giura",
        "rm": "Chantun Giura",
        "en": "Canton of Jura",
    },
    "LU": {
        "de": "Kanton Luzern",
        "fr": "Canton de Lucerne",
        "it": "Cantone di Lucerna",
        "rm": "Chantun Lucerna",
        "en": "Canton of Lucerne",
    },
    "NE": {
        "de": "Kanton Neuenburg",
        "fr": "Canton de Neuchâtel",
        "it": "Cantone di Neuchâtel",
        "rm": "Chantun Neuchâtel",
        "en": "Canton of Neuchâtel",
    },
    "NW": {
        "de": "Kanton Nidwalden",
        "fr": "Canton de Nidwald",
        "it": "Cantone di Nidvaldo",
        "rm": "Chantun Nidvalden",
        "en": "Canton of Nidwalden",
    },
    "OW": {
        "de": "Kanton Obwalden",
        "fr": "Canton d'Obwald",
        "it": "Cantone di Obvaldo",
        "rm": "Chantun Obwalda",
        "en": "Canton of Obwalden",
    },
    "SG": {
        "de": "Kanton St. Gallen",
        "fr": "Canton de Saint-Gall",
        "it": "Cantone di San Gallo",
        "rm": "Chantun Son Gagl",
        "en": "Canton of St. Gallen",
    },
    "SH": {
        "de": "Kanton Schaffhausen",
        "fr": "Canton de Schaffhouse",
        "it": "Cantone di Sciaffusa",
        "rm": "Chantun Schaffusa",
        "en": "Canton of Schaffhausen",
    },
    "SO": {
        "de": "Kanton Solothurn",
        "fr": "Canton de Soleure",
        "it": "Cantone di Soletta",
        "rm": "Chantun Soloturn",
        "en": "Canton of Solothurn",
    },
    "SZ": {
        "de": "Kanton Schwyz",
        "fr": "Canton de Schwytz",
        "it": "Cantone di Svitto",
        "rm": "Chantun Sviz",
        "en": "Canton of Schwyz",
    },
    "TG": {
        "de": "Kanton Thurgau",
        "fr": "Canton de Thurgovie",
        "it": "Cantone di Turgovia",
        "rm": "Chantun Turgovia",
        "en": "Canton of Thurgau",
    },
    "TI": {
        "de": "Kanton Tessin",
        "fr": "Canton du Tessin",
        "it": "Cantone Ticino",
        "rm": "Chantun Tessin",
        "en": "Canton of Ticino",
    },
    "UR": {
        "de": "Kanton Uri",
        "fr": "Canton d'Uri",
        "it": "Cantone di Uri",
        "rm": "Chantun Uri",
        "en": "Canton of Uri",
    },
    "VD": {
        "de": "Kanton Waadt",
        "fr": "Canton de Vaud",
        "it": "Cantone di Vaud",
        "rm": "Chantun Vad",
        "en": "Canton of Vaud",
    },
    "VS": {
        "de": "Kanton Wallis",
        "fr": "Canton du Valais",
        "it": "Cantone del Vallese",
        "rm": "Chantun Valais",
        "en": "Canton of Valais",
    },
    "ZG": {
        "de": "Kanton Zug",
        "fr": "Canton de Zoug",
        "it": "Cantone di Zugo",
        "rm": "Chantun Zug",
        "en": "Canton of Zug",
    },
    "ZH": {
        "de": "Kanton Zürich",
        "fr": "Canton de Zurich",
        "it": "Cantone di Zurigo",
        "rm": "Chantun Turitg",
        "en": "Canton of Zurich",
    },
    "FL": {
        "de": "Fürstentum Liechtenstein",
        "fr": "Principauté du Liechtenstein",
        "it": "Principato del Liechtenstein",
        "rm": "Principadi dal Liechtenstein",
        "en": "Principality of Liechtenstein",
    },
}
