# Generated by Django 6.0.2 on 2026-03-02 14:22

import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dataservice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dataservice_id",
                    utils.fields.CustomSlugField(
                        max_length=100, unique=True, verbose_name="External ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ogc:wms", "ogc:wms"),
                            ("ogc:wmts", "ogc:wmts"),
                            ("ogc:wfs", "ogc:wfs"),
                            ("ogcapi:features", "ogcapi:features"),
                            ("geoadmin:features", "geoadmin:features"),
                        ],
                        max_length=32,
                        verbose_name="Type",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Title")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the dataservice was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the dataservice was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "service_desc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shared.servicedesclink",
                    ),
                ),
                (
                    "service_doc",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shared.servicedoclink",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dataservice",
                "verbose_name_plural": "Dataservices",
            },
        ),
    ]
