# Generated by Django 6.0.2 on 2026-03-02 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataservice", "0001_initial"),
        ("shared", "0002_servicedesclink_link_id_servicedoclink_link_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataservice",
            name="service_desc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shared.servicedesclink",
            ),
        ),
        migrations.AlterField(
            model_name="dataservice",
            name="service_doc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shared.servicedoclink",
            ),
        ),
    ]
