# Generated by Django 6.0.2 on 2026-03-17 07:45

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataservice", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoadminFeaturesDataservice",
            fields=[
                (
                    "dataservice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dataservice.dataservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Geoadmin Features Dataservices",
                "verbose_name_plural": "Geoadmin Features Dataservices",
            },
            bases=("dataservice.dataservice",),
        ),
        migrations.CreateModel(
            name="OGCAPIFeaturesDataservice",
            fields=[
                (
                    "dataservice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dataservice.dataservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "OGC API Features Dataservices",
                "verbose_name_plural": "OGC API Features Dataservices",
            },
            bases=("dataservice.dataservice",),
        ),
        migrations.CreateModel(
            name="OGCAPIStacDataservice",
            fields=[
                (
                    "dataservice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dataservice.dataservice",
                    ),
                ),
                (
                    "landing_page_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the landing page of the OGC API STAC Dataservice",
                        max_length=500,
                        null=True,
                        verbose_name="Landing Page URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "OGC API STAC Dataservices",
                "verbose_name_plural": "OGC API STAC Dataservices",
            },
            bases=("dataservice.dataservice",),
        ),
        migrations.CreateModel(
            name="WFSDataservice",
            fields=[
                (
                    "dataservice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dataservice.dataservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "WFS Dataservices",
                "verbose_name_plural": "WFS Dataservices",
            },
            bases=("dataservice.dataservice",),
        ),
        migrations.CreateModel(
            name="WMSDataservice",
            fields=[
                (
                    "dataservice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dataservice.dataservice",
                    ),
                ),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32),
                        help_text="List of supported languages for the WMS Dataservice",
                        verbose_name="Supported Languages",
                    ),
                ),
                (
                    "capabilities_url",
                    models.URLField(
                        help_text="URL to the capabilities document of the WMS Dataservice. The URL can contain the following placeholders: {lang} for the different languages in which the WMS is available.",
                        max_length=500,
                        verbose_name="Capabilities URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMS Dataservices",
                "verbose_name_plural": "WMS Dataservices",
            },
            bases=("dataservice.dataservice",),
        ),
        migrations.CreateModel(
            name="WMTSDataservice",
            fields=[
                (
                    "dataservice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dataservice.dataservice",
                    ),
                ),
                (
                    "variable_epsg_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        help_text="List of the EPSG codes for the supported CRS of the WMTS Dataservice if {epsg} placeholder is used in the capabilities URL.",
                        verbose_name="List of supported CRS (EPSG codes)",
                    ),
                ),
                (
                    "capabilities_url",
                    models.URLField(
                        help_text="URL to the capabilities document of the WTMS Dataservice. The URL can contain the following placeholders: {epsg} for the different supported EPSG code.",
                        max_length=500,
                        verbose_name="Capabilities URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "WMTS Dataservices",
                "verbose_name_plural": "WMTS Dataservices",
            },
            bases=("dataservice.dataservice",),
        ),
        migrations.RemoveField(
            model_name="dataservice",
            name="describes",
        ),
        migrations.RemoveField(
            model_name="dataservice",
            name="linktemplates",
        ),
        migrations.RemoveField(
            model_name="dataservice",
            name="service_desc",
        ),
        migrations.RemoveField(
            model_name="dataservice",
            name="service_doc",
        ),
        migrations.RemoveField(
            model_name="dataservice",
            name="type",
        ),
        migrations.AddField(
            model_name="dataservice",
            name="documentation_url_de",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Documentation URL (DE)"
            ),
        ),
        migrations.AddField(
            model_name="dataservice",
            name="documentation_url_en",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Documentation URL (EN)"
            ),
        ),
        migrations.AddField(
            model_name="dataservice",
            name="documentation_url_fr",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Documentation URL (FR)"
            ),
        ),
        migrations.AddField(
            model_name="dataservice",
            name="documentation_url_it",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Documentation URL (IT)"
            ),
        ),
        migrations.AddField(
            model_name="dataservice",
            name="openapi_spec_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="OpenAPI Specification URL"
            ),
        ),
    ]
