# Generated by Django 6.0.2 on 2026-03-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataservice", "0002_alter_dataservice_service_desc_and_more"),
        ("shared", "0003_templatelink_alter_servicedesclink_link_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataservice",
            name="templated_links",
            field=models.ManyToManyField(blank=True, to="shared.templatelink"),
        ),
    ]
