# Generated by Django 6.0.2 on 2026-03-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataservice", "0003_dataservice_polymorphic_ctype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ogcapistacdataservice",
            name="landing_page_url",
            field=models.URLField(
                help_text="URL to the landing page of the OGC API STAC Dataservice",
                max_length=500,
                verbose_name="Landing Page URL",
            ),
        ),
    ]
