# Generated by Django 6.0.2 on 2026-03-02 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataservice", "0003_dataservice_templated_links"),
        ("shared", "0004_describeslink"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataservice",
            name="describes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shared.describeslink",
            ),
        ),
        migrations.AlterField(
            model_name="dataservice",
            name="type",
            field=models.CharField(
                choices=[
                    ("ogc:wms", "ogc:wms"),
                    ("ogc:wmts", "ogc:wmts"),
                    ("ogc:wfs", "ogc:wfs"),
                    ("ogcapi:features", "ogcapi:features"),
                    ("ogcapi:stac", "ogcapi:stac"),
                    ("geoadmin:features", "geoadmin:features"),
                ],
                max_length=32,
                verbose_name="Type",
            ),
        ),
    ]
