# Generated by Django 6.0.4 on 2026-05-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataservice", "0004_alter_ogcapistacdataservice_landing_page_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="geoadminfeaturesdataservice",
            name="landing_page_url",
            field=models.URLField(
                default="https://api3.geo.admin.ch/rest/services/ech/MapServer",
                help_text="URL to the landing page of the geoadmin features Dataservice (e.g. 'https://api3.geo.admin.ch/rest/services/ech/MapServer')",
                max_length=500,
                verbose_name="Landing Page URL",
            ),
        ),
    ]
