# Generated by Django 6.0.6 on 2026-06-26 13:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataservice", "0005_geoadminfeaturesdataservice_landing_page_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="wmsdataservice",
            name="default_language",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Default languages"
            ),
        ),
        migrations.AddField(
            model_name="wmtsdataservice",
            name="default_language",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Default languages"
            ),
        ),
        migrations.AddField(
            model_name="wmtsdataservice",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=list,
                help_text="List of supported languages for the WMS Dataservice",
                verbose_name="Supported Languages",
            ),
        ),
        migrations.AlterField(
            model_name="wmsdataservice",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=list,
                help_text="List of supported languages for the WMS Dataservice",
                verbose_name="Supported Languages",
            ),
        ),
        migrations.AlterField(
            model_name="wmtsdataservice",
            name="capabilities_url",
            field=models.URLField(
                help_text="URL to the capabilities document of the WTMS Dataservice. The URL can contain the following placeholders: {epsg} for the different supported EPSG code; {lang} for the different languages in which the WMS is available.",
                max_length=500,
                verbose_name="Capabilities URL",
            ),
        ),
    ]
