# Generated by Django 6.0.6 on 2026-07-09 12:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataservice", "0006_wmsdataservice_default_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataservice",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("user-input", "User Input (Via Admin Interface)"),
                    ("geodienste", "geodienste.ch"),
                ],
                default="user-input",
                max_length=255,
                verbose_name="Data Source",
            ),
        ),
        migrations.AddField(
            model_name="dataservice",
            name="data_source_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="List of original external IDs",
                verbose_name="Original IDs",
            ),
        ),
        migrations.AlterField(
            model_name="wmsdataservice",
            name="capabilities_url",
            field=models.URLField(
                help_text="URL to the capabilities document of the WMS Dataservice. The URL can contain the following placeholders: {lang} (2 letter ISO 639-1) or {lang3} (3 letter ISO 639-3) for the different languages in which the WMS is available.",
                max_length=500,
                verbose_name="Capabilities URL",
            ),
        ),
        migrations.AlterField(
            model_name="wmsdataservice",
            name="default_language",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="Default languages (2 letter ISO 639-1)",
            ),
        ),
        migrations.AlterField(
            model_name="wmsdataservice",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=list,
                help_text="List of supported languages (2 letter ISO 639-1) for the WMS Dataservice",
                verbose_name="Supported Languages",
            ),
        ),
        migrations.AlterField(
            model_name="wmtsdataservice",
            name="default_language",
            field=models.CharField(
                blank=True,
                max_length=2,
                null=True,
                verbose_name="Default languages (2 letter ISO 639-1)",
            ),
        ),
        migrations.AlterField(
            model_name="wmtsdataservice",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                blank=True,
                default=list,
                help_text="List of supported languages (2 letter ISO 639-1) for the WMS Dataservice",
                verbose_name="Supported Languages",
            ),
        ),
    ]
