# Generated by Django 6.0.2 on 2026-04-02 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Thesaurus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "thesaurus_id",
                    models.CharField(max_length=200, unique=True, verbose_name="External ID"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the thesaurus was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the thesaurus was last updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "thesauri",
                "ordering": ("thesaurus_id",),
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("keyword_id", models.CharField(max_length=200, verbose_name="External ID")),
                ("label_de", models.CharField(verbose_name="Label (German)")),
                ("label_fr", models.CharField(verbose_name="Label (French)")),
                ("label_en", models.CharField(verbose_name="Label (English)")),
                (
                    "label_it",
                    models.CharField(blank=True, null=True, verbose_name="Label (Italian)"),
                ),
                (
                    "label_rm",
                    models.CharField(blank=True, null=True, verbose_name="Label (Romansh)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the thesaurus was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the thesaurus was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "thesaurus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="thesaurus.thesaurus"
                    ),
                ),
            ],
            options={
                "ordering": ("thesaurus__thesaurus_id", "label_en"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("thesaurus", "keyword_id"), name="unique_keyword_id_per_thesaurus"
                    )
                ],
            },
        ),
    ]
