# Generated by Django 6.1.1 on 2026-09-09 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataset", "0017_remove_dataset_keywords"),
        ("thesaurus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Concept",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("concept_id", models.CharField(max_length=200, verbose_name="External ID")),
                ("label_de", models.CharField(verbose_name="Label (German)")),
                ("label_fr", models.CharField(verbose_name="Label (French)")),
                ("label_en", models.CharField(verbose_name="Label (English)")),
                (
                    "label_it",
                    models.CharField(blank=True, null=True, verbose_name="Label (Italian)"),
                ),
                (
                    "label_rm",
                    models.CharField(blank=True, null=True, verbose_name="Label (Romansh)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the thesaurus was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the thesaurus was last updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "ordering": ("thesaurus__thesaurus_id", "label_en"),
            },
        ),
        migrations.RemoveConstraint(
            model_name="keyword",
            name="unique_keyword_id_per_thesaurus",
        ),
        migrations.AddField(
            model_name="concept",
            name="thesaurus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="thesaurus.thesaurus"
            ),
        ),
        migrations.RemoveField(
            model_name="keyword",
            name="thesaurus",
        ),
        migrations.AddConstraint(
            model_name="concept",
            constraint=models.UniqueConstraint(
                fields=("thesaurus", "concept_id"), name="unique_concept_id_per_thesaurus"
            ),
        ),
        migrations.DeleteModel(
            name="Keyword",
        ),
    ]
