# Generated by Django 6.1.1 on 2026-09-09 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thesaurus", "0002_concept_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="thesaurus.concept",
            ),
        ),
    ]
