# Generated by Django 6.1.1 on 2026-09-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("thesaurus", "0003_concept_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="concept",
            name="order",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Order"),
        ),
    ]
