# Generated by Django 6.1.1 on 2026-09-22 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("thesaurus", "0004_concept_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concept",
            options={"ordering": ("thesaurus__thesaurus_id", "order")},
        ),
    ]
