[project]
name = "service-control"
version = "0.0.0" # NOTE: the version is not used
description = "Swissgeo control service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django~=5.2",
    "django-environ~=0.12",
    "django-ninja~=1.4",
    "ecs-logging~=2.2",
    "gevent~=25.4",
    "gunicorn~=23.0",
    "logging-utilities~=5.3",
    "psycopg[binary]~=3.2",
    "pyyaml~=6.0",
    "whitenoise~=6.11",
    "boto3~=1.42",
    "opentelemetry-sdk~=1.39",
    "opentelemetry-exporter-otlp~=1.39",
    "opentelemetry-instrumentation==0.60b1",
    "opentelemetry-instrumentation-botocore==0.60b1",
    "opentelemetry-instrumentation-django==0.60b1",
    "opentelemetry-instrumentation-logging==0.60b1",
    "opentelemetry-instrumentation-psycopg==0.60b1",
]

[dependency-groups]
dev = [
    "bandit",
    "debugpy",
    "django_debug_toolbar",
    "django-extensions",
    "django-stubs~=5.2",
    "isort",
    "mypy",
    "pylint",
    "pylint-django",
    "pytest",
    "pytest-cov",
    "pytest-django",
    "pytest-xdist",
    "types-gevent~=25.4",
    "types-gunicorn~=23.0",
    "yapf",
    "boto3-stubs[cognito-idp]~=1.42",
]

[tool.uv]
package = false # Do not install as a package
