# Generated by Django 6.0.2 on 2026-03-16 15:13

import django.core.validators
import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dataservice", "0002_geoadminfeaturesdataservice_and_more"),
        ("dataset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Distribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "distribution_id",
                    utils.fields.CustomSlugField(
                        max_length=100, unique=True, verbose_name="External ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("protocol", models.CharField(max_length=32, verbose_name="Protocol")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the distribution was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the distribution was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dataset.dataset"
                    ),
                ),
            ],
            options={
                "verbose_name": "Distributions",
                "verbose_name_plural": "Distributions",
            },
        ),
        migrations.CreateModel(
            name="ExternalStacDistribution",
            fields=[
                (
                    "distribution_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="distribution.distribution",
                    ),
                ),
                (
                    "stac_collection_id",
                    models.CharField(max_length=255, verbose_name="STAC Collection ID"),
                ),
                (
                    "dataservice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dataservice.ogcapistacdataservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "External STAC Distributions",
                "verbose_name_plural": "External STAC Distributions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataservice", "stac_collection_id"),
                        name="unique_stac_collection_id_per_dataservice",
                    )
                ],
            },
            bases=("distribution.distribution",),
        ),
        migrations.CreateModel(
            name="ExternalWMSDistribution",
            fields=[
                (
                    "distribution_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="distribution.distribution",
                    ),
                ),
                ("wms_layer_name", models.CharField(max_length=255, verbose_name="WMS Layer Name")),
                (
                    "opacity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Desired Opacity of the WMS layer when displayed in web app.",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Opacity",
                    ),
                ),
                (
                    "gutter",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Desired Gutter of the WMS layer when using tiled in web app.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(500),
                        ],
                        verbose_name="Gutter",
                    ),
                ),
                (
                    "dataservice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dataservice.wmsdataservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "External WMS Distributions",
                "verbose_name_plural": "External WMS Distributions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataservice", "wms_layer_name"),
                        name="unique_wms_layer_name_per_dataservice",
                    )
                ],
            },
            bases=("distribution.distribution",),
        ),
        migrations.CreateModel(
            name="ExternalWMTSDistribution",
            fields=[
                (
                    "distribution_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="distribution.distribution",
                    ),
                ),
                (
                    "wmts_layer_name",
                    models.CharField(max_length=255, verbose_name="WMTS Layer Name"),
                ),
                (
                    "opacity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Desired Opacity of the WMTS layer when displayed in web app.",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Opacity",
                    ),
                ),
                (
                    "dataservice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dataservice.wmtsdataservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "External WMTS Distributions",
                "verbose_name_plural": "External WMTS Distributions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataservice", "wmts_layer_name"),
                        name="unique_wmts_layer_name_per_dataservice",
                    )
                ],
            },
            bases=("distribution.distribution",),
        ),
    ]
