# Generated by Django 6.0.2 on 2026-03-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("distribution", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distribution",
            name="protocol",
        ),
        migrations.AddField(
            model_name="distribution",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
