# Generated by Django 6.0.2 on 2026-03-24 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distribution", "0002_remove_distribution_protocol_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalGeoJSONDistribution",
            fields=[
                (
                    "distribution_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="distribution.distribution",
                    ),
                ),
                (
                    "geojson_url_de",
                    models.URLField(max_length=2048, verbose_name="GeoJSON URL (DE)"),
                ),
                (
                    "geojson_url_fr",
                    models.URLField(
                        blank=True, max_length=2048, null=True, verbose_name="GeoJSON URL (FR)"
                    ),
                ),
                (
                    "geojson_url_it",
                    models.URLField(
                        blank=True, max_length=2048, null=True, verbose_name="GeoJSON URL (IT)"
                    ),
                ),
                (
                    "geojson_url_en",
                    models.URLField(
                        blank=True, max_length=2048, null=True, verbose_name="GeoJSON URL (EN)"
                    ),
                ),
                (
                    "geojson_url_rm",
                    models.URLField(
                        blank=True, max_length=2048, null=True, verbose_name="GeoJSON URL (RM)"
                    ),
                ),
                (
                    "style_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional URL to a style file for the GeoJSON layer.",
                        max_length=2048,
                        null=True,
                        verbose_name="Style URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "External GeoJSON Distributions",
                "verbose_name_plural": "External GeoJSON Distributions",
            },
            bases=("distribution.distribution",),
        ),
        migrations.AddField(
            model_name="distribution",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("bod-layers-js", "BOD (Layers JS)"),
                    (
                        "service-capabilities",
                        "Service Capabilities (e.g. WMS GetCapabilities, STAC API)",
                    ),
                    ("user-input", "User Input (Via Admin Interface)"),
                ],
                default="user-input",
                max_length=255,
                verbose_name="Data Source",
            ),
            preserve_default=False,
        ),
    ]
