# Generated by Django 6.0.4 on 2026-05-05 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataservice", "0005_geoadminfeaturesdataservice_landing_page_url"),
        ("distribution", "0003_externalgeojsondistribution_distribution_data_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalGeoadminFeaturesDistribution",
            fields=[
                (
                    "distribution_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="distribution.distribution",
                    ),
                ),
                (
                    "layer_id",
                    models.CharField(max_length=255, verbose_name="Geoadmin Features Layer ID"),
                ),
                (
                    "queryable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the layer is queryable (i.e. can be used in identify requests)",
                        verbose_name="Queryable",
                    ),
                ),
                (
                    "renderable",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the layer is renderable (i.e. has a html tooltip)",
                        verbose_name="Renderable",
                    ),
                ),
                (
                    "dataservice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dataservice.geoadminfeaturesdataservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Geoadmin Features Distributions",
                "verbose_name_plural": "External Geoadmin Features Distributions",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataservice", "layer_id"), name="unique_layer_id_per_dataservice"
                    )
                ],
            },
            bases=("distribution.distribution",),
        ),
    ]
