# Generated by Django 6.0.6 on 2026-06-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dataservice", "0006_wmsdataservice_default_language_and_more"),
        ("distribution", "0004_externalgeoadminfeaturesdistribution"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="externalwmsdistribution",
            name="unique_wms_layer_name_per_dataservice",
        ),
        migrations.RemoveConstraint(
            model_name="externalwmtsdistribution",
            name="unique_wmts_layer_name_per_dataservice",
        ),
        migrations.RenameField(
            model_name="externalwmsdistribution",
            old_name="wms_layer_name",
            new_name="wms_layer_name_de",
        ),
        migrations.RenameField(
            model_name="externalwmtsdistribution",
            old_name="wmts_layer_name",
            new_name="wmts_layer_name_de",
        ),
        migrations.AddConstraint(
            model_name="externalwmsdistribution",
            constraint=models.UniqueConstraint(
                fields=("dataservice", "wms_layer_name_de"),
                name="unique_wms_layer_name_per_dataservice",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalwmtsdistribution",
            constraint=models.UniqueConstraint(
                fields=("dataservice", "wmts_layer_name_de"),
                name="unique_wmts_layer_name_per_dataservice",
            ),
        ),
    ]
