# Generated by Django 6.0.6 on 2026-06-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "distribution",
            "0005_remove_externalwmsdistribution_unique_wms_layer_name_per_dataservice_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="externalwmsdistribution",
            name="wms_layer_name_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="WMS Layer Name (EN)"
            ),
        ),
        migrations.AddField(
            model_name="externalwmsdistribution",
            name="wms_layer_name_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="WMS Layer Name (FR)"
            ),
        ),
        migrations.AddField(
            model_name="externalwmsdistribution",
            name="wms_layer_name_it",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="WMS Layer Name (IT)"
            ),
        ),
        migrations.AddField(
            model_name="externalwmsdistribution",
            name="wms_layer_name_rm",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="WMS Layer Name (RM)"
            ),
        ),
        migrations.AddField(
            model_name="externalwmtsdistribution",
            name="wmts_layer_name_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="WMTS Layer Name (EN)"
            ),
        ),
        migrations.AddField(
            model_name="externalwmtsdistribution",
            name="wmts_layer_name_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="WMTS Layer Name (FR)"
            ),
        ),
        migrations.AddField(
            model_name="externalwmtsdistribution",
            name="wmts_layer_name_it",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="WMTS Layer Name (IT)"
            ),
        ),
        migrations.AddField(
            model_name="externalwmtsdistribution",
            name="wmts_layer_name_rm",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="WMTS Layer Name (RM)"
            ),
        ),
        migrations.AlterField(
            model_name="externalwmsdistribution",
            name="wms_layer_name_de",
            field=models.CharField(max_length=255, verbose_name="WMS Layer Name (default/DE)"),
        ),
        migrations.AlterField(
            model_name="externalwmtsdistribution",
            name="wmts_layer_name_de",
            field=models.CharField(max_length=255, verbose_name="WMTS Layer Name (default/DE)"),
        ),
    ]
