# Generated by Django 6.0.6 on 2026-07-20 11:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("distribution", "0006_externalwmsdistribution_wms_layer_name_en_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="distribution",
            old_name="title",
            new_name="title_de",
        ),
        migrations.AlterField(
            model_name="distribution",
            name="title_de",
            field=models.CharField(max_length=255, verbose_name="Title (German)"),
        ),
        migrations.AddField(
            model_name="distribution",
            name="description_de",
            field=models.TextField(blank=True, null=True, verbose_name="Description (German)"),
        ),
        migrations.AddField(
            model_name="distribution",
            name="description_en",
            field=models.TextField(blank=True, null=True, verbose_name="Description (English)"),
        ),
        migrations.AddField(
            model_name="distribution",
            name="description_fr",
            field=models.TextField(blank=True, null=True, verbose_name="Description (French)"),
        ),
        migrations.AddField(
            model_name="distribution",
            name="description_it",
            field=models.TextField(blank=True, null=True, verbose_name="Description (Italian)"),
        ),
        migrations.AddField(
            model_name="distribution",
            name="description_rm",
            field=models.TextField(blank=True, null=True, verbose_name="Description (Romansh)"),
        ),
        migrations.AddField(
            model_name="distribution",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title (English)"
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="title_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title (French)"
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="title_it",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title (Italian)"
            ),
        ),
        migrations.AddField(
            model_name="distribution",
            name="title_rm",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title (Romansh)"
            ),
        ),
    ]
