# Generated by Django 6.0.6 on 2026-07-20 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distribution", "0006_externalwmsdistribution_wms_layer_name_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalwmsdistribution",
            name="max_zoom",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28),
                ],
                verbose_name="Max zoom (as defined in the LV95 pyramid)",
            ),
        ),
        migrations.AddField(
            model_name="externalwmsdistribution",
            name="min_zoom",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28),
                ],
                verbose_name="Min zoom (as defined in the LV95 pyramid)",
            ),
        ),
        migrations.AddField(
            model_name="externalwmtsdistribution",
            name="max_zoom",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28),
                ],
                verbose_name="Max zoom (as defined in the LV95 pyramid)",
            ),
        ),
        migrations.AddField(
            model_name="externalwmtsdistribution",
            name="min_zoom",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(28),
                ],
                verbose_name="Min zoom (as defined in the LV95 pyramid)",
            ),
        ),
    ]
