# Generated by Django 6.0.6 on 2026-07-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distribution", "0007_rename_title_distribution_title_de"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="meta_information",
            field=models.BooleanField(
                default=False,
                help_text="Whether the layer holds meta information (rather than data)",
                verbose_name="Meta Information",
            ),
        ),
    ]
