# Generated by Django 6.0.8 on 2026-08-19 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collection", "0001_initial"),
        ("dataset", "0014_alter_dataset_data_source"),
        ("distribution", "0008_distribution_meta_information"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="distribution",
            name="description_de",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="description_fr",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="description_it",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="description_rm",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="meta_information",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="title_de",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="title_fr",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="title_it",
        ),
        migrations.RemoveField(
            model_name="distribution",
            name="title_rm",
        ),
        migrations.AddField(
            model_name="distribution",
            name="collection",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="collection.collection"
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="dataset",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="dataset.dataset"
            ),
        ),
    ]
