# Generated by Django 6.1 on 2026-08-26 06:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("distribution", "0008_distribution_meta_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="data_source_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="List of original external IDs",
                verbose_name="Original IDs",
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("bod-layers-js", "BOD (Layers JS)"),
                    (
                        "service-capabilities",
                        "Service Capabilities (e.g. WMS GetCapabilities, STAC API)",
                    ),
                    ("user-input", "User Input (Via Admin Interface)"),
                    ("geodienste", "geodienste.ch"),
                ],
                max_length=255,
                verbose_name="Data Source",
            ),
        ),
    ]
