# Generated by Django 6.0.6 on 2026-07-01 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GeopoliticalEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "geopolitical_entity_id",
                    models.IntegerField(
                        help_text="Stable external identifier of the geopolitical entity",
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("federal", "Federal"),
                            ("canton", "Canton"),
                            ("community", "Community"),
                            ("region", "Region"),
                            ("county", "County"),
                            ("corp", "Corporate"),
                        ],
                        default="community",
                        help_text="Describes the type / level of geopolitical unit",
                        max_length=255,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the GeopoliticalEntity (without type)",
                        max_length=255,
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The german name of the GeopoliticalEntity (without type)",
                        max_length=255,
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The french name of the GeopoliticalEntity (without type)",
                        max_length=255,
                    ),
                ),
                (
                    "name_it",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The italian name of the GeopoliticalEntity (without type)",
                        max_length=255,
                    ),
                ),
                (
                    "name_rm",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The romanish name of the GeopoliticalEntity (without type)",
                        max_length=255,
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Abbreviation or acronym of the name",
                        max_length=255,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the geopolitical entity was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the geopolitical entity was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to the parent geopolitical entity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="legal.geopoliticalentity",
                    ),
                ),
            ],
        ),
    ]
