# Generated by Django 6.0.6 on 2026-07-01 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geopoliticalentity",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to the parent geopolitical entity",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="legal.geopoliticalentity",
            ),
        ),
    ]
