# Generated by Django 6.0.6 on 2026-07-21 10:00

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0002_alter_geopoliticalentity_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geopoliticalentity",
            name="name",
        ),
        migrations.AlterField(
            model_name="geopoliticalentity",
            name="geopolitical_entity_id",
            field=utils.fields.CustomSlugField(
                help_text="Stable external identifier of the geopolitical entity",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="geopoliticalentity",
            name="type",
            field=models.CharField(
                choices=[
                    ("federal", "Federal"),
                    ("cantonal", "Cantonal"),
                    ("communal", "Communal"),
                    ("districtal", "Districtal"),
                    ("corporal", "Corporal"),
                ],
                default="communal",
                help_text="Describes the type / level of geopolitical unit",
                max_length=255,
            ),
        ),
    ]
