"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import environ
import yaml
from corsheaders.defaults import default_headers

from config.authorization import VPRole

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", default="") or None

# SECURITY:
# https://docs.djangoproject.com/en/dev/ref/settings/#secure-proxy-ssl-header
SECURE_PROXY_SSL_HEADER = ("HTTP_CLOUDFRONT_FORWARDED_PROTO", "https")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

CORS_ALLOWED_ORIGINS = env.list("CORS_ALLOWED_ORIGINS", default=[])
CORS_ALLOWED_ORIGIN_REGEXES = env.list("CORS_ALLOWED_ORIGIN_REGEXES", default=[])

CORS_ALLOW_HEADERS = list(default_headers) + env.list("CORS_ALLOW_HEADERS", default=[])

# Application definition
INSTALLED_APPS = [
    "oauth2_proxy",
    "polymorphic",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.staticfiles",
    "django.contrib.messages",
    "django.contrib.postgres",
    "corsheaders",
    "cognito",
    "verified_permissions",
    "support",
    "thesaurus",
    "organization",
    "dataset",
    "user",
    "harvest",
    "shared",
    "dataservice",
    "distribution",
    "legal",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "oauth2_proxy.middleware.Oauth2ProxyRemoteUserMiddleware",
    "oauth2_proxy.middleware.Oauth2ProxyRemoteMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTH_USER_MODEL = "user.CustomUser"

AUTHENTICATION_BACKENDS = [
    "oauth2_proxy.middleware.RemoteCustomUserBackend",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env.str("DB_NAME", "service_control"),
        "USER": env.str("DB_USER", "service_control"),
        "PASSWORD": env.str("DB_PW", "service_control"),
        "HOST": env.str("DB_HOST", "service_control"),
        "PORT": env.str("DB_PORT", "5432"),
        "OPTIONS": {},
        "TEST": {
            "NAME": env.str("DB_NAME_TEST", "test_service_control"),
        },
    },
}

# Database pool
# https://www.psycopg.org/psycopg3/docs/api/pool.html#the-connectionpool-class
DB_POOL = env.json("DB_POOL", default=None)
if DB_POOL:
    DATABASES["default"]["OPTIONS"]["pool"] = DB_POOL

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_HOST = env.str("DJANGO_STATIC_HOST", "")
STATIC_URL = f"{STATIC_HOST}/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


class BadSchemeError(Exception):
    """Exception that an URI scheme is not as expected."""

    def __init__(self, url: str) -> None:
        super().__init__(f"'{url}' must start with 'https://'")


def ensure_https(url: str | None) -> str | None:
    if url is None:
        return None
    if not url.startswith("https://"):
        raise BadSchemeError(url)
    return url


# oauth2-proxy
# List of groups that are allowed in django admin interface
OAUTH2_PROXY_URL_PREFIX = env.str("OAUTH2_PROXY_URL_PREFIX", "oauth2-proxy/")
OAUTH2_PROXY_COGNITO_URL = ensure_https(env.str("OAUTH2_PROXY_COGNITO_URL", "") or None)
OAUTH2_PROXY_COGNITO_APP_CLIENT_ID = env.str("OAUTH2_PROXY_COGNITO_APP_CLIENT_ID", "local")
OAUTH2_PROXY_EIAM_LOGOUT_URL = ensure_https(env.str("OAUTH2_PROXY_EIAM_LOGOUT_URL", "") or None)
OAUTH2_PROXY_DJANGO_ADMIN_GROUPS = env.list(
    "OAUTH2_PROXY_DJANGO_ADMIN_GROUPS",
    default=["swissgeo-admin"],
)
OAUTH2_PROXY_EXTRA_AUD_SSM_PARAM_NAME = env.str("OAUTH2_PROXY_EXTRA_AUD_SSM_PARAM_NAME", "") or None

# Only when running server locally to not connect to ssm parameter store
USE_LOCAL_SSM_STORE = env.bool("USE_LOCAL_SSM_STORE", False)
# Only when running server locally to not connect to verified permissions
USE_LOCAL_VERIFIED_PERMISSIONS = env.bool("USE_LOCAL_VERIFIED_PERMISSIONS", False)

# Cognito
COGNITO_ENDPOINT_URL = env.str("COGNITO_ENDPOINT_URL", "http://localhost:9229")
COGNITO_POOL_ID = env.str("COGNITO_POOL_ID", "local")

# Verified Permissions
VERIFIED_PERMISSIONS_STORE_ID = env.str("VERIFIED_PERMISSIONS_STORE_ID", "local")
VERIFIED_PERMISSIONS_NAMESPACE = env.str("VERIFIED_PERMISSIONS_NAMESPACE", "swissgeo")
# Map roles to aws verified permissions policy templates.
ROLE_POLICY_TEMPLATE_IDS = {
    VPRole.ORG_ADMIN: env.str("ORG_ADMIN_POLICY_TEMPLATE_ID", default="") or None,
    VPRole.DATASET_ADMIN: env.str("DATASET_ADMIN_POLICY_TEMPLATE_ID", default="") or None,
    VPRole.DATASET_CONTRIBUTOR: env.str("DATASET_CONTRIBUTOR_POLICY_TEMPLATE_ID", default="")
    or None,
}

# M2M
DEFAULT_M2M_TOKEN_DURATION_MINS = env.int("DEFAULT_M2M_TOKEN_DURATION_MINS", 15)
DEFAULT_M2M_SCOPE = env.str("DEFAULT_M2M_SCOPE", "") or None

# Testing
TESTING: bool = False


# Read configuration from file
def get_logging_config() -> dict[str, object]:
    """Read logging configuration
    Read and parse the yaml logging configuration file passed in the environment variable
    LOGGING_CFG and return it as dictionary
    Note: LOGGING_CFG is relative to the root of the repo
    """
    log_config_file = env.str("LOGGING_CFG", "config/logging-cfg-local.yaml")
    if log_config_file.lower() in ["none", "0", "", "false", "no"]:
        return {}
    log_config = {}
    with open(BASE_DIR / log_config_file, encoding="utf-8") as fd:
        log_config = yaml.safe_load(os.path.expandvars(fd.read()))
    return log_config or {}


LOGGING = get_logging_config()

# OTEL Settings
OTEL_SDK_DISABLED = env.bool("OTEL_SDK_DISABLED", False)

OTEL_ENABLE_OTLP_EXPORTER = env.bool("OTEL_ENABLE_OTLP_EXPORTER", True)
OTEL_EXPORTER_OTLP_ENDPOINT = env.str("OTEL_EXPORTER_OTLP_ENDPOINT", "http://localhost:4317")
OTEL_EXPORTER_OTLP_HEADERS = env.str("OTEL_EXPORTER_OTLP_HEADERS", default="") or None
OTEL_EXPORTER_OTLP_INSECURE = env.bool("OTEL_EXPORTER_OTLP_INSECURE", False)

OTEL_ENABLE_DJANGO = env.bool("OTEL_ENABLE_DJANGO", True)
OTEL_ENABLE_BOTO = env.bool("OTEL_ENABLE_BOTO", True)
OTEL_ENABLE_PSYCOPG = env.bool("OTEL_ENABLE_PSYCOPG", True)

# Path prefix for root (checker). Useful if the service is deployed under a
# specific path. Should end with a slash, for example  'service-control/'.
ROOT_PATH_PREFIX = env.str("ROOT_PATH_PREFIX", default="")

# Path prefix for admin ui. Should end with a slash, for example 'service-control/'.
ADMIN_PATH_PREFIX = env.str("ADMIN_PATH_PREFIX", default="")

# Path prefix for api endpoints. Should end with a slash, for example 'service-control/'.
API_PATH_PREFIX = env.str("API_PATH_PREFIX", default="api/")

# Django Admin interface logout redirect URL, if left empty it default to the django admin
# root domain
DJANGO_ADMIN_LOGOUT_REDIRECT_URL = env.str("DJANGO_ADMIN_LOGOUT_REDIRECT_URL", default="")
