"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import environ
import yaml

env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY', default=None)

# SECURITY:
# https://docs.djangoproject.com/en/dev/ref/settings/#secure-proxy-ssl-header
SECURE_PROXY_SSL_HEADER = ('HTTP_CLOUDFRONT_FORWARDED_PROTO', 'https')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

# Application definition
INSTALLED_APPS = [
    'oauth2_proxy',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.staticfiles',
    'django.contrib.messages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'oauth2_proxy.middleware.Oauth2ProxyRemoteUserMiddleware',
    'oauth2_proxy.middleware.Oauth2ProxyRemoteMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.RemoteUserBackend',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.str('DB_NAME', 'service_control'),
        'USER': env.str('DB_USER', 'service_control'),
        'PASSWORD': env.str('DB_PW', 'service_control'),
        'HOST': env.str('DB_HOST', 'service_control'),
        'PORT': env.str('DB_PORT', "5432"),
        'TEST': {
            'NAME': env.str('DB_NAME_TEST', 'test_service_control'),
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_HOST = env.str('DJANGO_STATIC_HOST', '')
STATIC_URL = f'{STATIC_HOST}/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


class BadScheme(Exception):
    """Exception that an URI scheme is not as expected."""


def ensure_https(url: str | None) -> str | None:
    if url is None:
        return None
    if not url.startswith("https://"):
        raise BadScheme(f"'{url}' must start with 'https://'")
    return url


# oauth2-proxy
# List of groups that are allowed in django admin interface
OAUTH2_PROXY_URL_PREFIX = env.str("OAUTH2_PROXY_URL_PREFIX", "oauth2-proxy/")
OAUTH2_PROXY_COGNITO_URL = ensure_https(env.str('OAUTH2_PROXY_COGNITO_URL', None))
OAUTH2_PROXY_COGNITO_APP_CLIENT_ID = env.str('OAUTH2_PROXY_COGNITO_APP_CLIENT_ID', 'local')
OAUTH2_PROXY_EIAM_LOGOUT_URL = ensure_https(env.str('OAUTH2_PROXY_EIAM_LOGOUT_URL', None))
OAUTH2_PROXY_DJANGO_ADMIN_GROUPS = env.list(
    'OAUTH2_PROXY_DJANGO_ADMIN_GROUPS', default=['swissgeo-admin']
)

# Testing
TESTING = False


# Read configuration from file
def get_logging_config() -> dict[str, object]:
    '''Read logging configuration
    Read and parse the yaml logging configuration file passed in the environment variable
    LOGGING_CFG and return it as dictionary
    Note: LOGGING_CFG is relative to the root of the repo
    '''
    log_config_file = env('LOGGING_CFG', default='config/logging-cfg-local.yaml')
    if log_config_file.lower() in ['none', '0', '', 'false', 'no']:
        return {}
    log_config = {}
    with open(BASE_DIR / log_config_file, 'rt', encoding="utf-8") as fd:
        log_config = yaml.safe_load(os.path.expandvars(fd.read()))
    return log_config or {}


LOGGING = get_logging_config()

# list of headers that are allowed to be logged
_DEFAULT_LOG_ALLOWED_HEADERS = [

    # Standard headers
    "accept",
    "accept-encoding",
    "accept-language",
    "accept-ranges",
    "cache-control",
    "connection",
    "content-length",
    "content-security-policy",
    "content-type",
    "etag",
    "host",
    "if-match",
    "if-none-match",
    "origin",
    "referer",
    "referrer-policy",
    "transfer-encoding",
    "user-agent",
    "vary",
    "x-content-type-options",
    "x-forwarded-for",
    "x-forwarded-host",
    "x-forwarded-port",
    "x-forwarded-proto",

  # Cloudfront headers
    "cloudfront-is-android-viewer",
    "cloudfront-is-desktop-viewer",
    "cloudfront-is-ios-viewer",
    "cloudfront-is-mobile-viewer",
    "cloudfront-is-smarttv-viewer",
    "cloudfront-is-tablet-viewer",

  # PPBGDI headers
    "x-e2e-testing",

  # API GW Headers
    "apigw-requestid"
]
LOG_ALLOWED_HEADERS = [
    str(header).lower()
    for header in env.list('LOG_ALLOWED_HEADERS', default=_DEFAULT_LOG_ALLOWED_HEADERS)
]

# Path prefix for all paths (checker, admin, api, etc.). Useful if the service is deployed under a
# specific path. Should end with a slash, for example  'service-control/'.
ROOT_PATH_PREFIX = env.str('ROOT_PATH_PREFIX', default='')
