# Generated by Django 6.0.4 on 2026-04-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatasetToUnitMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dataset_id_prefix",
                    models.CharField(max_length=100, verbose_name="Dataset ID Prefix"),
                ),
                (
                    "organization_id",
                    models.CharField(max_length=100, verbose_name="Organization ID"),
                ),
                (
                    "unit_id",
                    models.CharField(default="default", max_length=100, verbose_name="Unit ID"),
                ),
            ],
        ),
    ]
