# Generated by Django 6.0.4 on 2026-05-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harvest", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetToContactMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dataset_id_prefix",
                    models.CharField(max_length=100, verbose_name="Dataset ID Prefix"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("custodian", "Custodian"),
                            ("owner", "Owner"),
                            ("distributor", "Distributor"),
                            ("pointOfContact", "Point of Contact"),
                            ("publisher", "Publisher"),
                            ("resourceProvider", "Resource Provider"),
                            ("user", "User"),
                            ("originator", "Originator"),
                            ("principalInvestigator", "Principal Investigator"),
                            ("processor", "Processor"),
                            ("author", "Author"),
                            ("sponsor", "Sponsor"),
                            ("coAuthor", "Co-Author"),
                            ("collaborator", "Collaborator"),
                            ("editor", "Editor"),
                            ("mediator", "Mediator"),
                            ("rightsHolder", "Rights Holder"),
                            ("contributor", "Contributor"),
                            ("funder", "Funder"),
                            ("stakeholder", "Stakeholder"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "organization_id",
                    models.CharField(max_length=100, verbose_name="Organization ID"),
                ),
                (
                    "contact_name_en",
                    models.CharField(blank=True, null=True, verbose_name="Contact Name (EN)"),
                ),
            ],
        ),
    ]
