# Generated by Django 6.0.4 on 2026-05-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harvest", "0002_datasettocontactmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider_id_prefix",
                    models.CharField(max_length=100, verbose_name="Provider ID Prefix"),
                ),
                (
                    "organization_id",
                    models.CharField(max_length=100, verbose_name="Organization ID"),
                ),
                (
                    "update_organization",
                    models.BooleanField(
                        default=False,
                        help_text="Whetever the matching entry should update the organization",
                        verbose_name="Update organization",
                    ),
                ),
            ],
        ),
    ]
