# Generated by Django 6.0.5 on 2026-05-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harvest", "0003_organizationmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dataset_id_prefix",
                    models.CharField(max_length=100, verbose_name="Dataset ID Prefix (Harvest)"),
                ),
                ("dataset_id", models.CharField(max_length=100, verbose_name="Dataset ID (DB)")),
                (
                    "update_dataset",
                    models.BooleanField(
                        default=False,
                        help_text="Whetever the matching entry should update the dataset",
                        verbose_name="Update dataset",
                    ),
                ),
            ],
        ),
    ]
