# Generated by Django 6.0.6 on 2026-06-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("harvest", "0006_remove_datasetmapping_update_dataset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetmapping",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="datasettocontactmapping",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="datasettounitmapping",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="organizationmapping",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="datasetmapping",
            name="dataset_id_prefix",
            field=models.CharField(
                help_text="Prefix used for matching:<br>- Dataset ID during import of datasets from harvest table/BOD (if enabled)<br>- Layer ID during import of distributions from harvest table/BOD (if enabled)<br>- STAC Collection ID during syncing distributions from capabilities (if enabled)<br>- Base topic during import of datasets from geodienste",
                max_length=100,
                verbose_name="Prefix",
            ),
        ),
        migrations.AlterField(
            model_name="datasettocontactmapping",
            name="dataset_id_prefix",
            field=models.CharField(
                help_text="Prefix used for matching:<br>- Dataset ID during import of dataset contacts from harvest/geocat<br>- Dataset ID during import of dataset contacts from geodienste",
                max_length=100,
                verbose_name="Dataset ID Prefix",
            ),
        ),
        migrations.AlterField(
            model_name="datasettounitmapping",
            name="dataset_id_prefix",
            field=models.CharField(
                help_text="Prefix used for matching:<br>- Dataset ID during import of dataset units from harvest/BOD<br>- Dataset ID during import of dataset units from geodienste",
                max_length=100,
                verbose_name="Prefix",
            ),
        ),
        migrations.AlterField(
            model_name="organizationmapping",
            name="provider_id_prefix",
            field=models.CharField(
                help_text="Prefix used for matching:<br>- Provider ID during import of organizations from harvest table/BOD<br>- Canton/Broker during import of geodienste organizations, contacts, datasets",
                max_length=100,
                verbose_name="Prefix",
            ),
        ),
    ]
