upstream backend {
    server moto-server:5000;
}

map $http_accept_language $lang {
    default    "en";
    "~*\bde\b" "de";
    "~*\bfr\b" "fr";
    "~*\bit\b" "it";
}

server {
    listen 80;

    location / {
        set $lang $lang;

        if ($arg_language) {
            set $lang $arg_language;
        }

        rewrite ^(/.*) $1.$lang break;

        proxy_pass http://backend;
        proxy_set_header Host $host;

        add_header X-Language $lang always;
        add_header X-Proxied-URL $uri always;
    }
}
