upstream backend {
    server moto-server:5000;
}

server {
    listen 80;

    location / {
        if ($arg_language) {
            rewrite ^(/.+)$ $1.$arg_language break;
        }
        proxy_pass http://backend;
        proxy_set_header Host $host;
    }
}
