# Generated by Django 6.0.8 on 2026-08-19 06:43

import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dataset", "0014_alter_dataset_data_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "collection_id",
                    utils.fields.CustomSlugField(
                        max_length=100, unique=True, verbose_name="External ID"
                    ),
                ),
                ("title_de", models.CharField(max_length=255, verbose_name="Title (German)")),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title (French)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title (English)"
                    ),
                ),
                (
                    "title_it",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title (Italian)"
                    ),
                ),
                (
                    "title_rm",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title (Romansh)"
                    ),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True, verbose_name="Description (German)"),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, null=True, verbose_name="Description (French)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True, verbose_name="Description (English)"),
                ),
                (
                    "description_it",
                    models.TextField(blank=True, null=True, verbose_name="Description (Italian)"),
                ),
                (
                    "description_rm",
                    models.TextField(blank=True, null=True, verbose_name="Description (Romansh)"),
                ),
                (
                    "meta_information",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the layer holds meta information (rather than data)",
                        verbose_name="Meta Information",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("bod-layers-js", "BOD (Layers JS)"),
                            (
                                "service-capabilities",
                                "Service Capabilities (e.g. WMS GetCapabilities, STAC API)",
                            ),
                            ("user-input", "User Input (Via Admin Interface)"),
                        ],
                        max_length=255,
                        verbose_name="Data Source",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the collection was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the collection was last updated",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dataset.dataset"
                    ),
                ),
            ],
            options={
                "verbose_name": "Collections",
                "verbose_name_plural": "Collections",
            },
        ),
    ]
