# Generated by Django 6.0.2 on 2026-03-19 13:40

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0003_organization_vp_org_admin_policy_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "sub",
                    models.CharField(
                        help_text="Cognito subject. Either user id or app client id.",
                        max_length=150,
                        unique=True,
                        verbose_name="Sub",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=150, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Last Name"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email Address"),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="Staff Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date Joined"
                    ),
                ),
                (
                    "cognito_username",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Cognito Username",
                    ),
                ),
                (
                    "roles",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("org_admin", "ORG_ADMIN"),
                                ("dataset_admin", "DATASET_ADMIN"),
                                ("dataset_contributor", "DATASET_CONTRIBUTOR"),
                            ],
                            max_length=32,
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[("HUMAN", "Human"), ("MACHINE", "Machine")],
                        default="HUMAN",
                        max_length=10,
                        verbose_name="User Type",
                    ),
                ),
                (
                    "vp_machine_user_policy_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Verified Permissions Policy ID",
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
