# Generated by Django 5.2.10 on 2026-01-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "machine_user_id",
                    models.CharField(db_index=True, unique=True, verbose_name="Client ID"),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("name", models.CharField(verbose_name="Name")),
                ("created_by_user", models.CharField(verbose_name="Create By User")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organization.organization"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "name"),
                        name="user_machineuser_organization_name_uniq",
                        violation_error_message="machine user with this name already exists",
                    )
                ],
            },
        ),
    ]
