# Generated by Django 6.0.2 on 2026-03-23 10:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanUser",
            fields=[],
            options={
                "verbose_name": "Human User",
                "verbose_name_plural": "Human Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.customuser",),
        ),
        migrations.CreateModel(
            name="MachineUser",
            fields=[],
            options={
                "verbose_name": "Machine User",
                "verbose_name_plural": "Machine Users",
                "ordering": ("last_name",),
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.customuser",),
        ),
    ]
