# Generated by Django 5.2.10 on 2026-01-20 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="machineuser",
            unique_together={("organization", "name")},
        ),
    ]
