# Generated by Django 6.0.2 on 2026-03-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_humanuser_machineuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machineuser",
            options={
                "ordering": ("name",),
                "verbose_name": "Machine User",
                "verbose_name_plural": "Machine Users",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Name"),
        ),
    ]
