# Generated by Django 6.0.2 on 2026-02-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_customuser_delete_user"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="machineuser",
            name="user_machineuser_organization_name_uniq",
        ),
        migrations.AddField(
            model_name="customuser",
            name="created_by_user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="user.customuser"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("User model", " Context"), ("HUMAN", "Human"), ("MACHINE", "Machine")],
                default="HUMAN",
                max_length=10,
                verbose_name="User Type",
            ),
        ),
        migrations.DeleteModel(
            name="MachineUser",
        ),
    ]
