# Generated by Django 6.0.2 on 2026-03-27 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_unit_vp_dataset_admin_policy_id_and_more"),
        ("user", "0003_alter_machineuser_options_customuser_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.unit",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.organization",
            ),
        ),
    ]
