# Generated by Django 5.2.10 on 2026-02-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_customuser_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("role_id", models.CharField(db_index=True, unique=True, verbose_name="Role ID")),
                ("name", models.CharField(db_index=True, unique=True, verbose_name="Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
            ],
        ),
    ]
