# Generated by Django 6.0.2 on 2026-04-02 07:39

import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_unit_vp_dataset_admin_policy_id_and_more"),
        ("user", "0004_customuser_unit_alter_customuser_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "access_request_id",
                    utils.fields.CustomSlugField(
                        db_index=True,
                        default=utils.fields.CustomSlugField.generate_unique_slug,
                        max_length=100,
                        unique=True,
                        verbose_name="Access Request ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("DECLINED", "Declined"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="State",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organization.organization"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.humanuser"
                    ),
                ),
            ],
        ),
    ]
