# Generated by Django 5.2.10 on 2026-02-13 09:37
from typing import TYPE_CHECKING

from django.db import migrations

if TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_roles(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor") -> None:
    # We can't import the Role model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Role = apps.get_model("user", "Role")
    Role.objects.create(
        role_id="org_admin",
        name="Organization Admin",
        description="Organization administrator with full access to all resources.",
    )
    Role.objects.create(
        role_id="dataset_admin",
        name="Dataset Admin",
        description="Dataset administrator with full access to all datasets of their Unit.",
    )
    Role.objects.create(
        role_id="dataset_contributor",
        name="Dataset Contributor",
        description="Dataset contributor with limited access to datasets of their Unit.",
    )


def remove_roles(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor") -> None:
    # We can't import the Role model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Role = apps.get_model("user", "Role")
    Role.objects.filter(role_id="org_admin").delete()
    Role.objects.filter(role_id="dataset_admin").delete()
    Role.objects.filter(role_id="dataset_contributor").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_role"),
    ]

    operations = [
        migrations.RunPython(code=create_roles, reverse_code=remove_roles),
    ]
