# Generated by Django 6.0.2 on 2026-03-02 13:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_remove_machineuser_user_machineuser_organization_name_uniq_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("org_admin", "Organization Admin"),
                        ("dataset_admin", "Dataset Admin"),
                        ("dataset_contributor", "Dataset Contributor"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("HUMAN", "Human"), ("MACHINE", "Machine")],
                default="HUMAN",
                max_length=10,
                verbose_name="User Type",
            ),
        ),
    ]
