# Generated by Django 6.0.2 on 2026-02-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_auto_20260213_0937"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="roles",
            field=models.ManyToManyField(blank=True, to="user.role"),
        ),
    ]
