# Generated by Django 6.0.2 on 2026-03-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_alter_customuser_created_by_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="vp_machine_user_policy_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Verified Permissions Policy ID"
            ),
        ),
    ]
