# Generated by Django 6.0.2 on 2026-03-12 15:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_customuser_vp_machine_user_policy_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("org_admin", "ORG_ADMIN"),
                        ("dataset_admin", "DATASET_ADMIN"),
                        ("dataset_contributor", "DATASET_CONTRIBUTOR"),
                    ],
                    max_length=32,
                ),
                blank=True,
                default=list,
            ),
        ),
    ]
