# Generated by Django 6.0.2 on 2026-03-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_alter_customuser_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cognito_username",
            field=models.CharField(
                blank=True, max_length=100, null=True, unique=True, verbose_name="Cognito Username"
            ),
        ),
    ]
