# Generated by Django 6.0.2 on 2026-03-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceDescLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("href", models.URLField(max_length=2048)),
                ("rel", models.CharField(max_length=30)),
                ("link_type", models.CharField(blank=True, max_length=150, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("hreflang", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the dataset was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the dataset was last updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceDocLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("href", models.URLField(max_length=2048)),
                ("rel", models.CharField(max_length=30)),
                ("link_type", models.CharField(blank=True, max_length=150, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("hreflang", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the dataset was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the dataset was last updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
