# Generated by Django 6.0.2 on 2026-03-03 19:55

import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DescribesLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "link_id",
                    utils.fields.CustomSlugField(
                        blank=True, max_length=100, unique=True, verbose_name="External ID"
                    ),
                ),
                ("href", models.URLField(max_length=2048)),
                ("rel", models.CharField(max_length=30)),
                ("link_type", models.CharField(blank=True, max_length=150, null=True)),
                ("title", models.CharField(max_length=255)),
                ("hreflang", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the dataset was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the dataset was last updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceDescLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "link_id",
                    utils.fields.CustomSlugField(
                        blank=True, max_length=100, unique=True, verbose_name="External ID"
                    ),
                ),
                ("href", models.URLField(max_length=2048)),
                ("rel", models.CharField(max_length=30)),
                ("link_type", models.CharField(blank=True, max_length=150, null=True)),
                ("title", models.CharField(max_length=255)),
                ("hreflang", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the dataset was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the dataset was last updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServiceDocLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "link_id",
                    utils.fields.CustomSlugField(
                        blank=True, max_length=100, unique=True, verbose_name="External ID"
                    ),
                ),
                ("href", models.URLField(max_length=2048)),
                ("rel", models.CharField(max_length=30)),
                ("link_type", models.CharField(blank=True, max_length=150, null=True)),
                ("title", models.CharField(max_length=255)),
                ("hreflang", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the dataset was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the dataset was last updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TemplateLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "templatelink_id",
                    utils.fields.CustomSlugField(
                        blank=True, max_length=100, unique=True, verbose_name="External ID"
                    ),
                ),
                (
                    "uri_template",
                    models.URLField(
                        help_text="URI template with variables in curly braces. For example: https://example.com/datasets/{dataset_id}",
                        max_length=2048,
                    ),
                ),
                ("rel", models.CharField(max_length=30)),
                ("link_type", models.CharField(blank=True, max_length=150, null=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the dataset was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the dataset was last updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateLinkVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "variable_name",
                    models.CharField(
                        help_text="Name of the variable in the URI template, without curly braces",
                        max_length=32,
                    ),
                ),
                (
                    "variable_dict",
                    models.JSONField(
                        blank=True,
                        help_text="JSON field to store the variable dictionary",
                        null=True,
                    ),
                ),
                (
                    "template_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="shared.templatelink",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("template_link", "variable_name"),
                        name="unique_variable_per_template_link",
                    )
                ],
            },
        ),
    ]
