# Generated by Django 6.0.2 on 2026-03-02 14:33

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicedesclink",
            name="link_id",
            field=utils.fields.CustomSlugField(
                default="a", max_length=100, unique=True, verbose_name="External ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicedoclink",
            name="link_id",
            field=utils.fields.CustomSlugField(
                default="b", max_length=100, unique=True, verbose_name="External ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="servicedesclink",
            name="title",
            field=models.CharField(default="title", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="servicedoclink",
            name="title",
            field=models.CharField(default="title", max_length=255),
            preserve_default=False,
        ),
    ]
