# Generated by Django 6.0.2 on 2026-03-02 21:20

import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shared", "0003_templatelink_alter_servicedesclink_link_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DescribesLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "link_id",
                    utils.fields.CustomSlugField(
                        blank=True, max_length=100, unique=True, verbose_name="External ID"
                    ),
                ),
                ("href", models.URLField(max_length=2048)),
                ("rel", models.CharField(max_length=30)),
                ("link_type", models.CharField(blank=True, max_length=150, null=True)),
                ("title", models.CharField(max_length=255)),
                ("hreflang", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the dataset was created",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the dataset was last updated",
                        verbose_name="Updated at",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
