# Generated by Django 5.2.10 on 2026-02-10 10:51

import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "unit_id",
                    utils.fields.CustomSlugField(
                        db_index=True, max_length=100, unique=True, verbose_name="External ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("name_de", models.CharField(verbose_name="Name (German)")),
                ("name_fr", models.CharField(verbose_name="Name (French)")),
                ("name_en", models.CharField(verbose_name="Name (English)")),
                ("name_it", models.CharField(blank=True, null=True, verbose_name="Name (Italian)")),
                ("name_rm", models.CharField(blank=True, null=True, verbose_name="Name (Romansh)")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organization.organization"
                    ),
                ),
            ],
        ),
    ]
