# Generated by Django 6.0.2 on 2026-03-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0002_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="vp_org_admin_policy_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Verified Permissions Policy ID for org_admin",
            ),
        ),
    ]
