# Generated by Django 6.0.3 on 2026-04-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_unit_vp_dataset_admin_policy_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="Updated")),
                ("name_de", models.CharField(blank=True, null=True, verbose_name="Name (German)")),
                ("name_fr", models.CharField(blank=True, null=True, verbose_name="Name (French)")),
                ("name_en", models.CharField(blank=True, null=True, verbose_name="Name (English)")),
                ("name_it", models.CharField(blank=True, null=True, verbose_name="Name (Italian)")),
                ("name_rm", models.CharField(blank=True, null=True, verbose_name="Name (Romansh)")),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email"),
                ),
                ("phone", models.CharField(blank=True, null=True, verbose_name="Phone")),
                (
                    "address_administrative_area",
                    models.CharField(
                        blank=True, null=True, verbose_name="Address: Administrative Area"
                    ),
                ),
                (
                    "address_delivery_point",
                    models.CharField(blank=True, null=True, verbose_name="Address: Delivery Point"),
                ),
                (
                    "address_postal_code",
                    models.CharField(blank=True, null=True, verbose_name="Address: Postal Code"),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, null=True, verbose_name="Address: City"),
                ),
                (
                    "address_country",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="Address: Country"
                    ),
                ),
                (
                    "url_de",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="URL (German)"
                    ),
                ),
                (
                    "url_fr",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="URL (German)"
                    ),
                ),
                (
                    "url_en",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="URL (German)"
                    ),
                ),
                (
                    "url_it",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="URL (German)"
                    ),
                ),
                (
                    "url_rm",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="URL (German)"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="organization.organization"
                    ),
                ),
            ],
            options={
                "ordering": ("organization__organization_id", "name_en"),
            },
        ),
    ]
