# Generated by Django 6.0.4 on 2026-05-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("bod-contact-organization", "BOD (contactorganization)"),
                    ("user-input", "User Input (Admin UI/API)"),
                ],
                default="user-input",
                max_length=255,
                verbose_name="Data Source",
            ),
        ),
    ]
