# Generated by Django 6.0.4 on 2026-05-06 08:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0006_organization_data_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="data_source_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="List of original external IDs",
                verbose_name="Original IDs",
            ),
        ),
    ]
