# Generated by Django 6.0.6 on 2026-06-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0007_organization_data_source_ids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="url_en",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL (English)"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="url_fr",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL (French)"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="url_it",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL (Italian)"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="url_rm",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="URL (Romansh)"
            ),
        ),
    ]
