# Generated by Django 6.0.5 on 2026-06-03 13:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0008_alter_contact_url_en_alter_contact_url_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("geocat", "Geocat"),
                    ("user-input", "User Input (Admin UI/API)"),
                    ("geodienste", "geodienste.ch"),
                ],
                default="user-input",
                max_length=255,
                verbose_name="Data Source",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="data_source_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                help_text="List of original external IDs",
                verbose_name="Original IDs",
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="legacy_contact",
            field=models.TextField(
                blank=True, null=True, verbose_name="Free Text Contact (Legacy)"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="data_source",
            field=models.CharField(
                choices=[
                    ("bod-contact-organization", "BOD (contactorganization)"),
                    ("user-input", "User Input (Admin UI/API)"),
                    ("geodienste", "geodienste.ch"),
                ],
                default="user-input",
                max_length=255,
                verbose_name="Data Source",
            ),
        ),
    ]
