# Generated by Django 6.1.1 on 2026-09-15 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("legal", "0003_remove_geopoliticalentity_name_and_more"),
        ("organization", "0009_contact_data_source_contact_data_source_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="geopolitical_entity",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="legal.geopoliticalentity",
            ),
        ),
    ]
